 name: flutter_firebase
 description: "A new Flutter project."
 publish_to: 'none'

 version: 1.0.0+1

 environment:
  sdk: '>=3.0.0 <4.0.0'

 dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  fl_chart: ^0.68.0

  cupertino_icons: ^1.0.8

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.15.0
  
  flutter_local_notifications: ^17.0.0

  provider: ^6.1.5
  file_picker: ^8.0.7
  firebase_storage: ^11.7.7
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

 dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

 flutter:
  uses-material-design: true
